name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile document.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: test.tex
      - name: Upload the artifact
        uses: actions/upload-artifact@master
        with:
          name: test.pdf
          path: ../
