name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile document.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: test.tex
      - name: Publish LaTeX
        run : |
          git config --global user.email "prvnpa4@gmail.com"
          git config --global user.name "Praveen"
          git add -f $PWD/*.pdf
          git commit -m "WORKFLOW_COMMIT - Update PDFs [skip ci]"
          git push
